"""Workflow cluster discovery — replaces the permit_type taxonomy.

Sessions are grouped by greedy cosine similarity over their action-trace
embeddings. A cluster reaching MIN_CLUSTER_SIZE triggers an
OPTIMIZATION_OPPORTUNITY. Cluster labels are auto-generated by a single
Gemini summarization call when a cluster crosses the threshold.

This is the site-agnostic replacement for SessionRecord.permit_type.
"""
from __future__ import annotations
import os
import time
from dataclasses import dataclass
from typing import Optional
from uuid import uuid4

from google import genai
from sqlmodel import Session, select

from models.session import SessionRecord
from services.embedding_service import embedding_service
from services.exceptions import QuotaExhaustedException
from services.log_streamer import logger

CLUSTER_THRESHOLD = float(os.getenv("CLUSTER_THRESHOLD", "0.85"))
MIN_CLUSTER_SIZE = int(os.getenv("MIN_CLUSTER_SIZE", "3"))


@dataclass
class ClusterAssignment:
    cluster_id: str
    cluster_label: Optional[str]
    cluster_size: int  # total members including the just-assigned session
    crossed_threshold: bool  # True if this session pushed the cluster to >= MIN_CLUSTER_SIZE


class ClusterService:
    def __init__(self):
        self._client: Optional[genai.Client] = None

    @property
    def client(self) -> genai.Client:
        if self._client is None:
            self._client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
        return self._client

    async def assign_cluster(
        self,
        new_session: SessionRecord,
        db: Session,
    ) -> ClusterAssignment:
        """Assign a cluster to a freshly-completed session.

        Strategy: find the most similar prior clustered session. If similarity
        >= CLUSTER_THRESHOLD, join that cluster. Else start a new singleton.
        Generate a cluster_label via Gemini the first time the cluster reaches
        MIN_CLUSTER_SIZE.
        """
        if not new_session.embedding:
            logger.warning(
                f"[Cluster] Session {new_session.session_id} has no embedding — skipping"
            )
            return ClusterAssignment(cluster_id=str(uuid4()), cluster_label=None,
                                     cluster_size=1, crossed_threshold=False)

        # Find the best-matching existing clustered session
        prior_clustered = db.exec(
            select(SessionRecord).where(
                SessionRecord.cluster_id != None,  # noqa: E711
                SessionRecord.session_id != new_session.session_id,
                SessionRecord.completed_at != None,  # noqa: E711
            )
        ).all()

        best_match: Optional[SessionRecord] = None
        best_score = 0.0
        for prior in prior_clustered:
            if not prior.embedding:
                continue
            score = embedding_service.cosine_similarity(new_session.embedding, prior.embedding)
            if score > best_score:
                best_score = score
                best_match = prior

        if best_match and best_score >= CLUSTER_THRESHOLD:
            cluster_id = best_match.cluster_id
            existing_label = best_match.cluster_label
            logger.info(
                f"[Cluster] {new_session.session_id} joins cluster {cluster_id[:8]} "
                f"(via {best_match.session_id}, cosine={best_score:.3f})"
            )
        else:
            cluster_id = str(uuid4())
            existing_label = None
            logger.info(
                f"[Cluster] {new_session.session_id} starts new cluster {cluster_id[:8]} "
                f"(best prior cosine={best_score:.3f}, threshold={CLUSTER_THRESHOLD})"
            )

        new_session.cluster_id = cluster_id
        new_session.cluster_label = existing_label
        db.add(new_session)
        db.commit()

        # Recount cluster size (include the just-added session)
        members = db.exec(
            select(SessionRecord).where(SessionRecord.cluster_id == cluster_id)
        ).all()
        size = len(members)

        crossed = False
        if existing_label is None and size >= MIN_CLUSTER_SIZE:
            try:
                label = await self._generate_label(members)
            except QuotaExhaustedException:
                raise
            except Exception as exc:
                logger.warning(f"[Cluster] Label generation failed: {exc}")
                label = self._fallback_label(members)
            # Backfill the label onto every member
            for m in members:
                m.cluster_label = label
                db.add(m)
            db.commit()
            new_session.cluster_label = label
            existing_label = label
            crossed = True
            logger.info(
                f"[Cluster] {cluster_id[:8]} reached size {size} — labelled \"{label}\""
            )
        elif existing_label is not None and size >= MIN_CLUSTER_SIZE:
            # Cluster is already established and labeled. Every new session
            # that joins it is another repetition of the same pattern —
            # surface the optimization opportunity again so the sidebar
            # prompts the worker. (AGENT_MATCH_FOUND pre-empts this if a
            # published agent already covers the pattern.)
            crossed = True

        return ClusterAssignment(
            cluster_id=cluster_id,
            cluster_label=existing_label,
            cluster_size=size,
            crossed_threshold=crossed,
        )

    async def _generate_label(self, members: list[SessionRecord]) -> str:
        """One Gemini call to summarize what the cluster's workflow does."""
        # Use the first 3 members' event sequences as representative samples
        samples = members[:3]
        sample_blocks = []
        for i, s in enumerate(samples, start=1):
            events_summary = "\n".join(
                f"  [{e.get('event_type')}] {e.get('screen_name')} "
                f"{e.get('element_selector', '')[:60]} "
                f"{('=' + str(e.get('element_value'))[:40]) if e.get('element_value') else ''}"
                for e in (s.events or [])[:20]
            )
            sample_blocks.append(f"Session {i} ({s.session_id}):\n{events_summary}")

        prompt = (
            "You are labelling a discovered workflow cluster for a UI-automation "
            "system. The cluster contains the following representative sessions:\n\n"
            + "\n\n".join(sample_blocks)
            + "\n\nReturn a single short phrase (max 6 words) that names this "
            "workflow from the user's perspective — what task does it accomplish? "
            "Plain text only, no quotes, no punctuation at the end."
        )

        t0 = time.time()
        try:
            response = await self.client.aio.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
                config={"max_output_tokens": 30},
            )
        except Exception as e:
            msg = str(e)
            if any(k in msg for k in ("429", "quota", "RESOURCE_EXHAUSTED", "Quota")):
                raise QuotaExhaustedException(msg) from e
            raise
        latency_ms = int((time.time() - t0) * 1000)
        label = (response.text or "").strip().strip('"').strip("'").rstrip(".")
        logger.info(
            f"[Cluster] gemini-2.5-flash label generated | {latency_ms}ms | \"{label}\""
        )
        return label or self._fallback_label(members)

    def _fallback_label(self, members: list[SessionRecord]) -> str:
        # Use the first session's first non-navigate screen name as a hint
        for s in members:
            for e in (s.events or []):
                screen = e.get("screen_name", "")
                if screen and screen != "UNKNOWN_SCREEN":
                    return f"workflow {screen.lower().replace('_', ' ')}"
        return "workflow"


cluster_service = ClusterService()
