import re

with open("frontend/src/sidebar/SidebarApp.tsx", "r", encoding="utf-8") as f:
    code = f.read()

# Remove the dynamic CLR object generated by `isDark` inside SidebarApp
code = re.sub(r"  const CLR = isDark \? \{.*?\} : \{.*?\}\n", "", code, flags=re.DOTALL)

# Add the CSS variables style applying
code = re.sub(
    r"return \(\s*<div style=\{root\}>\s*\{/\* Header \*/\}",
    """  const themeProps = isDark ? {
    '--clr-bg': '#09090b',
    '--clr-surface': '#18181b',
    '--clr-border': '#27272a',
    '--clr-text': '#f4f4f5',
    '--clr-dim': '#a1a1aa',
    '--clr-accent': '#FF7E67',
    '--clr-green': '#10b981',
    '--clr-amber': '#f59e0b',
    '--clr-red': '#ef4444',
  } : {
    '--clr-bg': '#f8fafc',
    '--clr-surface': '#ffffff',
    '--clr-border': '#e2e8f0',
    '--clr-text': '#0f172a',
    '--clr-dim': '#64748b',
    '--clr-accent': '#FF7E67',
    '--clr-green': '#059669',
    '--clr-amber': '#d97706',
    '--clr-red': '#dc2626',
  }
  
  return (
    <div style={{ ...root, ...(themeProps as any) }}>
      {/* Header */}""",
    code,
    flags=re.DOTALL
)

# Insert the global CLR constant mapping to CSS variables
global_clr = """
const CLR = {
  bg: 'var(--clr-bg)',
  surface: 'var(--clr-surface)',
  border: 'var(--clr-border)',
  text: 'var(--clr-text)',
  dim: 'var(--clr-dim)',
  accent: 'var(--clr-accent)',
  green: 'var(--clr-green)',
  amber: 'var(--clr-amber)',
  red: 'var(--clr-red)',
}

const root: React.CSSProperties = {"""

code = re.sub(r"const root: React\.CSSProperties = \{", global_clr, code)

with open("frontend/src/sidebar/SidebarApp.tsx", "w", encoding="utf-8") as f:
    f.write(code)

print("done")
